site_name: Veetility Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - Utility Functions : UtilityFunctions.md
  - Cleaning : CleaningFunction.md
  - Quality Assessment: QAFunctions.md
  - View Through Rate: ViewThroughRate.md
  - Slack Notifier: SlackNotifier.md
  - Snowflake : snowflake.md
  - V Lift:  V_lift.md
  - Logger : Logger.md
  - Tutorials: tutorials.md