site_name: Veetility Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - Other Vayner Libraries: OtherVaynerLibraries.md
  - UtilityFunctions Methods: UtilityFunctions.md
  - SlackNotifier Methods: SlackNotifier.md
  - Snowflake Methods: snowflake.md
  - V Lift:  V_lift.md
  - Logger Methods: Logger.md
  - Tutorials: tutorials.md