site_name: Veetility Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Veetility Docs: index.md
  - tutorials.md
  - Getting Started: getting_started.md
  - UtilityFunctions Methods: UtilityFunctions.md
  - SlackNotifier Methods: SlackNotifier.md
  - Logger Methods: Logger.md
  - explanation.md