site_name: Veetility Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - Utility Functions Methods: UtilityFunctions.md
  - Cleaning Functions Methods: CleaningFunction.md
  - QA Functions Methods: QAFunctions.md
  - View Through Rate: ViewThroughRate.md
  - Slack Notifier Methods: SlackNotifier.md
  - Snowflake Methods: snowflake.md
  - V Lift:  V_lift.md
  - Logger Methods: Logger.md
  - Tutorials: tutorials.md