site_name: Veetility Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - Utility Functions : UtilityFunctions.md
  - Cleaning : CleaningFunctions.md
  - Quality Assessment: QAFunctions.md
  - View Through Rate: ViewThroughRate.md
  - Slack Notifier: SlackNotifier.md
  - Email Functions: vee_mails.md
  - Snowflake : snowflake.md
  - S3Bucket : S3Bucket.md
  - LinkedIn API : LinkedIn_API.md